In [1]:
import pandas as pd
import numpy as np

In [2]:
density_df = pd.read_csv("../../Resources/Neighborhood_Race_Density.csv")
household_df = pd.read_csv("../../Resources/Neighborhood_Household_Data.csv")

In [3]:
d_df = density_df[["Area", "Total Population", 
                 'Occupied Housing Units',  
                 'Percent Owner Occupied Housing Units',
                 'Gross Population Density, Persons Per Acre',
                 'Density Ranking',
                 'ACRES']]
d_df2 = d_df[d_df["Gross Population Density, Persons Per Acre"] != 0]
new_df = d_df2[d_df2["Area"] != "UT"]
density_final = new_df.rename(columns={"Occupied Housing Units" : "Total Households"})
density_final

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES
0,ALLENDALE,"6,643","3,263",64.10%,5.1,60,"1,303.50"
1,ANDERSON MILL,"28,473","10,904",67.30%,5.0,62,"5,706.40"
2,AVERY RANCH--LAKELINE,"14,785","5,681",60.50%,3.2,74,"4,641.40"
3,BARTON CREEK MALL,"5,147","2,076",63.70%,2.2,84,"2,318.10"
4,BARTON HILLS,"8,022","4,614",31.40%,3.9,70,"2,038.10"
...,...,...,...,...,...,...,...
98,WINDSOR HILLS,"7,089","2,275",51.60%,9.0,16,790.5
99,WINDSOR PARK,"15,086","5,599",40.10%,9.8,13,"1,532.30"
100,WINDSOR ROAD,"2,985","1,225",77.80%,5.5,55,545.6
101,WOOTEN,"5,339","2,027",43.60%,8.6,22,621
102,ZILKER,"5,779","3,174",47.60%,7.7,28,747

In [4]:
h_df = household_df.loc[:,'Neighborhood Reporting Area': '% Single Mother Households']
h_df.dropna(thresh=2,inplace=True)
new_h_df = h_df[["Neighborhood Reporting Area",
                 "Total Population",
                 "Total Households",
                 "Household Size", 
                 "Family Households",
                 "Non-Family Households",
                 "% Families w/ Children",
                 "% Single Mother Households"]]
household_final = new_h_df.rename(columns={"Neighborhood Reporting Area":"Area"})
household_final

,Area,Total Population,Total Households,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
0,ALLENDALE,"6,643","3,263",2.0,"1,650","1,613",22.2%,3.3%
1,ANDERSON MILL,"28,473","10,904",2.6,"7,812","3,092",37.0%,5.4%
2,AVERY RANCH--LAKELINE,"14,785","5,681",2.6,"3,878","1,803",43.5%,5.2%
3,BARTON CREEK MALL,"5,147","2,076",2.5,"1,359",717,34.6%,4.5%
4,BARTON HILLS,"8,022","4,614",1.7,"1,445","3,169",12.1%,2.6%
...,...,...,...,...,...,...,...,...
94,WINDSOR HILLS,"7,089","2,275",3.0,"1,488",787,33.7%,8.0%
95,WINDSOR PARK,"15,086","5,599",2.7,"3,167","2,432",28.7%,9.2%
96,WINDSOR ROAD,"2,985","1,225",2.4,769,456,35.3%,3.8%
97,WOOTEN,"5,339","2,027",2.6,"1,197",830,29.7%,7.7%
98,ZILKER,"5,779","3,174",1.8,"1,155","2,019",16.1%,4.5%

In [5]:
merge_df = pd.merge(density_final, household_final, on=['Area', 'Total Population', 'Total Households'], how='outer')
merge_df.dropna(inplace=True)
merge_df["Total Population"] = merge_df["Total Population"].str.replace(",","").astype('int')
merge_df["Total Households"] = merge_df["Total Households"].str.replace(",","").astype('int')
merge_df["ACRES"] = merge_df["ACRES"].str.replace(",","").astype('float')
merge_df["Family Households"] = merge_df["Family Households"].str.replace(",","").astype('int')
merge_df["Non-Family Households"] = merge_df["Non-Family Households"].str.replace(",","").astype('int')
merge_df["Percent Owner Occupied Housing Units"] = merge_df["Percent Owner Occupied Housing Units"].str.replace("%","").astype('float')/100.0
merge_df["% Families w/ Children"] = merge_df["% Families w/ Children"].str.replace("%","").astype('float')/100.0
merge_df["% Single Mother Households"] = merge_df["% Single Mother Households"].str.replace("%","").astype('float')/100.0
merge_df

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
0,ALLENDALE,6643,3263,0.641,5.1,60.0,1303.5,2.0,1650,1613,0.222,0.033
1,ANDERSON MILL,28473,10904,0.673,5.0,62.0,5706.4,2.6,7812,3092,0.370,0.054
2,AVERY RANCH--LAKELINE,14785,5681,0.605,3.2,74.0,4641.4,2.6,3878,1803,0.435,0.052
3,BARTON CREEK MALL,5147,2076,0.637,2.2,84.0,2318.1,2.5,1359,717,0.346,0.045
4,BARTON HILLS,8022,4614,0.314,3.9,70.0,2038.1,1.7,1445,3169,0.121,0.026
...,...,...,...,...,...,...,...,...,...,...,...,...
93,WINDSOR HILLS,7089,2275,0.516,9.0,16.0,790.5,3.0,1488,787,0.337,0.080
94,WINDSOR PARK,15086,5599,0.401,9.8,13.0,1532.3,2.7,3167,2432,0.287,0.092
95,WINDSOR ROAD,2985,1225,0.778,5.5,55.0,545.6,2.4,769,456,0.353,0.038
96,WOOTEN,5339,2027,0.436,8.6,22.0,621.0,2.6,1197,830,0.297,0.077
97,ZILKER,5779,3174,0.476,7.7,28.0,747.0,1.8,1155,2019,0.161,0.045

In [6]:
#City of Austin Averages for colummns
density_avg = merge_df["Gross Population Density, Persons Per Acre"].mean()
owner_occupied = merge_df["Percent Owner Occupied Housing Units"].mean()
house_size = merge_df["Household Size"].mean()
fam = merge_df["Family Households"].sum()
non_fam = merge_df["Non-Family Households"].sum()
percent_fam = fam / (fam+non_fam)
children = merge_df["% Families w/ Children"].mean()
mother = merge_df["% Single Mother Households"].mean()

stats = ["Austin", density_avg, owner_occupied, house_size, percent_fam, children, mother]

In [15]:
#Downtown Averages
zip_78701 = merge_df[merge_df["Area"] == "DOWNTOWN"]
density_78701 = zip_78701["Gross Population Density, Persons Per Acre"].mean()
owner_78701 = zip_78701["Percent Owner Occupied Housing Units"].mean()
house_78701 = zip_78701["Household Size"].mean()
fam_78701 = zip_78701["Family Households"].sum()
non_fam_78701 = zip_78701["Non-Family Households"].sum()
percent_fam_78701 = fam_78701 / (fam_78701+non_fam_78701)
children_78701 = zip_78701["% Families w/ Children"].mean()
mother_78701 = zip_78701["% Single Mother Households"].mean()

stats_78701 = ["78701", density_78701, owner_78701, house_78701, percent_fam_78701, children_78701, mother_78701]

zip_78701

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
22,DOWNTOWN,7635,4379,0.333,6.8,44.0,1117.2,1.5,908,3471,0.036,0.009

In [8]:
zip_78741 = merge_df[(merge_df["Area"] == "RIVERSIDE")|
               (merge_df["Area"] == "MONTOPOLIS")|
               (merge_df["Area"] == "PARKER LANE")|
               (merge_df["Area"] == "PLEASANT VALLEY")]


density_78741 = zip_78741["Gross Population Density, Persons Per Acre"].mean()
owner_78741 = zip_78741["Percent Owner Occupied Housing Units"].mean()
house_78741 = zip_78741["Household Size"].mean()
fam_78741 = zip_78741["Family Households"].sum()
non_fam_78741 = zip_78741["Non-Family Households"].sum()
percent_fam_78741 = fam_78741 / (fam_78741+non_fam_78741)
children_78741 = zip_78741["% Families w/ Children"].mean()
mother_78741 = zip_78741["% Single Mother Households"].mean()

stats_78741 = ["78741", density_78741, owner_78741, house_78741, percent_fam_78741, children_78741, mother_78741]


zip_78741

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
50,MONTOPOLIS,10638,3152,0.468,7.4,35.0,1446.3,3.3,2312,840,0.409,0.175
62,PARKER LANE,9581,4396,0.160,8.4,24.0,1133.9,2.2,1751,2645,0.216,0.086
64,PLEASANT VALLEY,12618,5163,0.050,8.8,18.0,1438.2,2.4,1302,3861,0.136,0.057
66,RIVERSIDE,12012,4961,0.091,16.7,3.0,719.8,2.4,2169,2792,0.262,0.101

In [9]:
zip_78704 = merge_df[(merge_df["Area"] == "BOULDIN")|
               (merge_df["Area"] == "BARTON HILLS")|
               (merge_df["Area"] == "DAWSON")|
               (merge_df["Area"] == "GALINDO")|
               (merge_df["Area"] == "SOUTH LAMAR")|
               (merge_df["Area"] == "ST. EDWARDS")|
               (merge_df["Area"] == "SOUTH RIVER CITY")|
               (merge_df["Area"] == "ZILKER")
              ]

density_78704 = zip_78704["Gross Population Density, Persons Per Acre"].mean()
owner_78704 = zip_78704["Percent Owner Occupied Housing Units"].mean()
house_78704 = zip_78704["Household Size"].mean()
fam_78704 = zip_78704["Family Households"].sum()
non_fam_78704 = zip_78704["Non-Family Households"].sum()
percent_fam_78704 = fam_78704 / (fam_78704+non_fam_78704)
children_78704 = zip_78704["% Families w/ Children"].sum()
mother_78704 = zip_78704["% Single Mother Households"].sum()

stats_78704 = ["78704", density_78704, owner_78704, house_78704, percent_fam_78704, children_78704, mother_78704]


zip_78704

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
4,BARTON HILLS,8022,4614,0.314,3.9,70.0,2038.1,1.7,1445,3169,0.121,0.026
6,BOULDIN,5510,2694,0.404,7.1,38.0,773.3,2.0,1024,1670,0.182,0.084
18,DAWSON,2670,1273,0.372,8.5,23.0,315.2,2.1,491,782,0.145,0.034
28,GALINDO,3512,1745,0.338,8.1,26.0,433.5,2.0,640,1105,0.157,0.054
74,SOUTH LAMAR,8152,4264,0.187,10.5,10.0,777.7,1.9,1307,2957,0.145,0.051
76,SOUTH RIVER CITY,6511,3559,0.346,8.9,17.0,733.2,1.8,1090,2469,0.137,0.053
79,ST. EDWARDS,5322,2045,0.118,7.4,33.0,719.6,2.0,660,1385,0.158,0.054
97,ZILKER,5779,3174,0.476,7.7,28.0,747.0,1.8,1155,2019,0.161,0.045

In [10]:
zip_78753 = merge_df[(merge_df["Area"] == "NORTH LAMAR")|
               (merge_df["Area"] == "WINDSOR HILLS")|
               (merge_df["Area"] == "HERITAGE HILLS")|
               (merge_df["Area"] == "GEORGIA ACRES")]

density_78753 = zip_78753["Gross Population Density, Persons Per Acre"].mean()
owner_78753 = zip_78753["Percent Owner Occupied Housing Units"].mean()
house_78753 = zip_78753["Household Size"].mean()
fam_78753 = zip_78753["Family Households"].sum()
non_fam_78753 = zip_78753["Non-Family Households"].sum()
percent_fam_78753 = fam_78753 / (fam_78753+non_fam_78753)
children_78753 = zip_78753["% Families w/ Children"].mean()
mother_78753 = zip_78753["% Single Mother Households"].mean()

stats_78753 = ["78753", density_78753, owner_78753, house_78753, percent_fam_78753, children_78753, mother_78753]

zip_78753

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
31,GEORGIA ACRES,8559,3128,0.148,12.7,7.0,676.2,2.7,1783,1345,0.355,0.110
36,HERITAGE HILLS,5853,1938,0.348,6.8,45.0,864.8,3.0,1280,658,0.424,0.115
54,NORTH LAMAR,6478,1948,0.267,10.3,11.0,627.8,3.3,1371,577,0.440,0.117
93,WINDSOR HILLS,7089,2275,0.516,9.0,16.0,790.5,3.0,1488,787,0.337,0.080

In [11]:
zip_78758 = merge_df[(merge_df["Area"] == "NORTH BURNET")|
               (merge_df["Area"] == "GRACY WOODS")|
               (merge_df["Area"] == "NACA")]

density_78758 = zip_78758["Gross Population Density, Persons Per Acre"].mean()
owner_78758 = zip_78758["Percent Owner Occupied Housing Units"].mean()
house_78758 = zip_78758["Household Size"].mean()
fam_78758 = zip_78758["Family Households"].sum()
non_fam_78758 = zip_78758["Non-Family Households"].sum()
percent_fam_78758 = fam_78758 / (fam_78758+non_fam_78758)
children_78758 = zip_78758["% Families w/ Children"].mean()
mother_78758 = zip_78758["% Single Mother Households"].mean()

stats_78758 = ["78758", density_78758, owner_78758, house_78758, percent_fam_78758, children_78758, mother_78758]

zip_78758

,Area,Total Population,Total Households,Percent Owner Occupied Housing Units,"Gross Population Density, Persons Per Acre",Density Ranking,ACRES,Household Size,Family Households,Non-Family Households,% Families w/ Children,% Single Mother Households
33,GRACY WOODS,28220,12659,0.442,6.4,47.0,4412.6,2.2,6564,6095,0.235,0.063
52,NACA,28604,9578,0.293,14.6,5.0,1953.7,3.0,6213,3365,0.379,0.111
53,NORTH BURNET,4472,2554,0.012,2.1,85.0,2088.1,1.8,777,1777,0.143,0.044

In [22]:
summary_df = pd.DataFrame(np.array([stats, stats_78701, stats_78741, stats_78704, stats_78753, stats_78758]),
                          columns=['Area', "Gross Population Density, Persons Per Acre", "Percent Owner Occupied Housing Units", "Household Size", "% Family Households", "% Families w/ Children", "% Single Mother Households"])
summary_df[["Gross Population Density, Persons Per Acre", "Percent Owner Occupied Housing Units", "Household Size", "% Family Households", "% Families w/ Children", "% Single Mother Households"]] = summary_df[["Gross Population Density, Persons Per Acre", "Percent Owner Occupied Housing Units", "Household Size", "% Family Households", "% Families w/ Children", "% Single Mother Households"]].astype(float).round(2)
summary_df

,Area,"Gross Population Density, Persons Per Acre",Percent Owner Occupied Housing Units,Household Size,% Family Households,% Families w/ Children,% Single Mother Households
0,Austin,6.31,0.46,2.40,0.52,0.26,0.07
1,78701,6.80,0.33,1.50,0.21,0.04,0.01
2,78741,10.32,0.19,2.58,0.43,0.26,0.10
3,78704,7.76,0.32,1.91,0.33,1.21,0.40
4,78753,9.70,0.32,3.00,0.64,0.39,0.11
5,78758,7.70,0.25,2.33,0.55,0.25,0.07