In [3]:
#Dependencies
import pandas_profiling as pp
from pandas_profiling import ProfileReport
import pandas as pd
from functools import reduce

In [4]:
df = pd.read_csv("cleaned_data_09_19.csv")

In [5]:
df.head(10)

,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date,Occurred Time,Location Type,Address,Zip Code,Council District,APD Sector,Census Tract,Clearance Status,Clearance Date,Category Description,Latitude,Longitude
0,CHILD CUSTODY INTERFERE,2001,N,2019-04-13,0,RESIDENCE / HOME,9500 DESSAU RD,78753.0,4.0,ED,18.33,NaN,NaN,NaN,30.352493,-97.675258
1,RUNAWAY CHILD,4100,N,2019-04-13,23,OTHER / UNKNOWN,3708 S 2ND ST,78704.0,3.0,DA,13.07,NaN,NaN,NaN,30.230056,-97.771030
2,CRIMINAL TRESPASS,2716,N,2019-04-13,1805,DEPARTMENT / DISCOUNT STORE,1030 NORWOOD PARK BLVD,78753.0,4.0,ID,18.13,C,4/13/19,NaN,30.339153,-97.691169
3,POCKET PICKING,605,N,2019-04-13,100,BAR / NIGHT CLUB,403 E 6TH ST,78701.0,9.0,GE,11.00,NaN,NaN,Theft,30.266787,-97.739181
4,THEFT BY SHOPLIFTING,607,N,2019-04-13,1050,LIQUOR STORE,8311 RESEARCH BLVD SVRD NB,78758.0,4.0,ED,18.05,NaN,NaN,Theft,30.356603,-97.715282
5,HARASSMENT,2703,N,2019-04-13,1100,RESIDENCE / HOME,10007 QUAIL VALLEY BLVD,78758.0,4.0,ED,18.21,NaN,NaN,NaN,30.377012,-97.709570
6,BURGLARY OF VEHICLE,601,N,2019-04-13,135,STREETS / HWY / ROAD / ALLEY,RED RIVER ST / E 15TH ST,78701.0,1.0,BA,7.00,NaN,NaN,Theft,30.275346,-97.733910
7,ASSAULT BY CONTACT,902,N,2019-04-13,1245,GOVERNMENT / PUBLIC BUILDING,4110 GUADALUPE ST,78751.0,9.0,BA,2.03,NaN,NaN,NaN,30.307651,-97.735350
8,CRIMINAL MISCHIEF,1400,N,2019-04-13,1430,SHOPPING MALL,12636 RESEARCH BLVD SVRD SB,78759.0,10.0,AD,17.56,NaN,NaN,NaN,30.431368,-97.764789
9,BURGLARY OF VEHICLE,601,N,2019-04-13,1200,BANKS / SAVINGS & LOAN,140 W SLAUGHTER LN,78748.0,2.0,FR,24.21,NaN,NaN,Theft,30.167463,-97.790525

In [6]:
datetime = pd.to_datetime( df.loc[0:0]["Occurred Date"] )

In [7]:
df["Datetime"] = pd.to_datetime( df["Occurred Date"])

In [8]:
df = df.set_index("Datetime")

In [9]:
df.to_csv("cleaned_data_with_datetime_09_19.csv")

In [10]:
df.head()

,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date,Occurred Time,Location Type,Address,Zip Code,Council District,APD Sector,Census Tract,Clearance Status,Clearance Date,Category Description,Latitude,Longitude
Datetime,,,,,,,,,,,,,,,,
2019-04-13,CHILD CUSTODY INTERFERE,2001,N,2019-04-13,0,RESIDENCE / HOME,9500 DESSAU RD,78753.0,4.0,ED,18.33,NaN,NaN,NaN,30.352493,-97.675258
2019-04-13,RUNAWAY CHILD,4100,N,2019-04-13,23,OTHER / UNKNOWN,3708 S 2ND ST,78704.0,3.0,DA,13.07,NaN,NaN,NaN,30.230056,-97.771030
2019-04-13,CRIMINAL TRESPASS,2716,N,2019-04-13,1805,DEPARTMENT / DISCOUNT STORE,1030 NORWOOD PARK BLVD,78753.0,4.0,ID,18.13,C,4/13/19,NaN,30.339153,-97.691169
2019-04-13,POCKET PICKING,605,N,2019-04-13,100,BAR / NIGHT CLUB,403 E 6TH ST,78701.0,9.0,GE,11.00,NaN,NaN,Theft,30.266787,-97.739181
2019-04-13,THEFT BY SHOPLIFTING,607,N,2019-04-13,1050,LIQUOR STORE,8311 RESEARCH BLVD SVRD NB,78758.0,4.0,ED,18.05,NaN,NaN,Theft,30.356603,-97.715282

In [11]:
print("Incidents per year")
for year in range(2009,2019):
    print( f"Number of incidents in {year}: {len(df[df.index.year==year])}")

Incidents per year
Number of incidents in 2009: 74418
Number of incidents in 2010: 72304
Number of incidents in 2011: 65853
Number of incidents in 2012: 64542
Number of incidents in 2013: 62395
Number of incidents in 2014: 58125
Number of incidents in 2015: 56070
Number of incidents in 2016: 44996
Number of incidents in 2017: 41981
Number of incidents in 2018: 47326

In [12]:

for year in range(2009,2019):
    print( f'Family violence incidents in {year}: {len(df[ (df["Family Violence"]=="Y") & (df.index.year==year) ])}')

Family violence incidents in 2009: 4484
Family violence incidents in 2010: 4120
Family violence incidents in 2011: 3556
Family violence incidents in 2012: 3435
Family violence incidents in 2013: 3056
Family violence incidents in 2014: 2865
Family violence incidents in 2015: 3055
Family violence incidents in 2016: 2754
Family violence incidents in 2017: 2742
Family violence incidents in 2018: 3438

In [13]:
for year in range(2009,2019):
    print( f'Number of clearances in {year}: {len(df[ (df["Clearance Status"]=="C") & (df.index.year==year) ])}')

Number of clearances in 2009: 18727
Number of clearances in 2010: 17225
Number of clearances in 2011: 18681
Number of clearances in 2012: 19024
Number of clearances in 2013: 18233
Number of clearances in 2014: 16681
Number of clearances in 2015: 14803
Number of clearances in 2016: 12436
Number of clearances in 2017: 12260
Number of clearances in 2018: 11124

In [14]:
for year in range(2009,2019):
    print( f'Percentage of clearances in {year}: {len(df[ (df["Clearance Status"]=="C") & (df.index.year==year) ])/len(df[df.index.year==year])*100}')

Percentage of clearances in 2009: 25.16461071246204
Percentage of clearances in 2010: 23.823025005532198
Percentage of clearances in 2011: 28.367728121725662
Percentage of clearances in 2012: 29.47538037247064
Percentage of clearances in 2013: 29.221892779870185
Percentage of clearances in 2014: 28.69849462365591
Percentage of clearances in 2015: 26.400927412163366
Percentage of clearances in 2016: 27.638012267757134
Percentage of clearances in 2017: 29.203687382387272
Percentage of clearances in 2018: 23.505050078181128

In [15]:
df[df.index.year==2009]["Highest Offense Description"].value_counts()[0:10]

BURGLARY OF VEHICLE               8056
THEFT                             6946
FAMILY DISTURBANCE                5307
CRIMINAL MISCHIEF                 4586
BURGLARY OF RESIDENCE             3420
ASSAULT W/INJURY-FAM/DATE VIOL    2829
HARASSMENT                        2818
PUBLIC INTOXICATION               2365
DISTURBANCE - OTHER               2160
CUSTODY ARREST TRAFFIC WARR       2035
Name: Highest Offense Description, dtype: int64

In [16]:
for year in range(2009,2019):
    print(f'Top ten offense types for {year}: \n\n{df[df.index.year==year]["Highest Offense Description"].value_counts()[0:10]}\n\n')

Top ten offense types for 2009:

BURGLARY OF VEHICLE               8056
THEFT                             6946
FAMILY DISTURBANCE                5307
CRIMINAL MISCHIEF                 4586
BURGLARY OF RESIDENCE             3420
ASSAULT W/INJURY-FAM/DATE VIOL    2829
HARASSMENT                        2818
PUBLIC INTOXICATION               2365
DISTURBANCE - OTHER               2160
CUSTODY ARREST TRAFFIC WARR       2035
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2010:

BURGLARY OF VEHICLE               6740
THEFT                             6527
FAMILY DISTURBANCE                5173
CRIMINAL MISCHIEF                 4185
BURGLARY OF RESIDENCE             3418
HARASSMENT                        2606
ASSAULT W/INJURY-FAM/DATE VIOL    2598
CUSTODY ARREST TRAFFIC WARR       2255
PUBLIC INTOXICATION               2211
DWI                               2128
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2011:

BURGLARY OF VEHICLE               5731
THEFT                             5667
FAMILY DISTURBANCE                4305
CRIMINAL MISCHIEF                 3400
PUBLIC INTOXICATION               3025
WARRANT ARREST NON TRAFFIC        2236
ASSAULT W/INJURY-FAM/DATE VIOL    2198
HARASSMENT                        2149
DWI                               2048
CUSTODY ARREST TRAFFIC WARR       2033
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2012:

THEFT                             5827
BURGLARY OF VEHICLE               5741
FAMILY DISTURBANCE                4705
CRIMINAL MISCHIEF                 3429
THEFT BY SHOPLIFTING              2420
PUBLIC INTOXICATION               2395
DISTURBANCE - OTHER               2232
DWI                               2163
ASSAULT W/INJURY-FAM/DATE VIOL    2112
WARRANT ARREST NON TRAFFIC        2093
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2013:

THEFT                             5603
BURGLARY OF VEHICLE               5261
FAMILY DISTURBANCE                5006
CRIMINAL MISCHIEF                 2903
THEFT BY SHOPLIFTING              2483
DISTURBANCE - OTHER               2302
DWI                               2258
PUBLIC INTOXICATION               2235
ASSAULT W/INJURY-FAM/DATE VIOL    1955
WARRANT ARREST NON TRAFFIC        1933
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2014:

THEFT                             5163
FAMILY DISTURBANCE                4945
BURGLARY OF VEHICLE               4352
CRIMINAL MISCHIEF                 2788
THEFT BY SHOPLIFTING              2324
WARRANT ARREST NON TRAFFIC        2114
DWI                               2080
DISTURBANCE - OTHER               1977
PUBLIC INTOXICATION               1853
ASSAULT W/INJURY-FAM/DATE VIOL    1790
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2015:

THEFT                             5118
FAMILY DISTURBANCE                4525
BURGLARY OF VEHICLE               4056
CRIMINAL MISCHIEF                 2781
THEFT BY SHOPLIFTING              2110
DWI                               1944
DISTURBANCE - OTHER               1884
WARRANT ARREST NON TRAFFIC        1816
ASSAULT W/INJURY-FAM/DATE VIOL    1709
PUBLIC INTOXICATION               1670
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2016:

FAMILY DISTURBANCE                4487
THEFT                             3063
CRIMINAL MISCHIEF                 2634
BURGLARY OF VEHICLE               2378
DWI                               1716
DISTURBANCE - OTHER               1692
ASSAULT W/INJURY-FAM/DATE VIOL    1439
PUBLIC INTOXICATION               1344
WARRANT ARREST NON TRAFFIC        1328
ASSAULT WITH INJURY               1198
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2017:

FAMILY DISTURBANCE                4370
THEFT                             2407
BURGLARY OF VEHICLE               2348
CRIMINAL MISCHIEF                 2220
DWI                               1554
DISTURBANCE - OTHER               1513
ASSAULT W/INJURY-FAM/DATE VIOL    1452
ASSAULT WITH INJURY               1258
POSS MARIJUANA                    1185
PUBLIC INTOXICATION               1168
Name: Highest Offense Description, dtype: int64


Top ten offense types for 2018:

FAMILY DISTURBANCE                5016
BURGLARY OF VEHICLE               4273
THEFT                             3791
CRIMINAL MISCHIEF                 2340
ASSAULT W/INJURY-FAM/DATE VIOL    1664
DISTURBANCE - OTHER               1650
DWI                               1504
HARASSMENT                        1322
ASSAULT WITH INJURY               1293
THEFT BY SHOPLIFTING              1161
Name: Highest Offense Description, dtype: int64

In [17]:
for year in range(2009,2019):
    print(f'Top ten location types with most crimes reported in {year}: \n\n{df[df.index.year==year]["Location Type"].value_counts().iloc[0:10]}\n\n')

Top ten location types with most crimes reported in 2009:

RESIDENCE / HOME                31755
STREETS / HWY / ROAD / ALLEY    16405
PARKING LOTS / GARAGE            9488
COMMERCIAL / OFFICE BUILDING     6390
DEPARTMENT / DISCOUNT STORE      1071
OTHER / UNKNOWN                  1059
CONVENIENCE STORE                1047
GOVERNMENT / PUBLIC BUILDING      916
RESTAURANTS                       891
GROCERY / SUPERMARKET             859
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2010:

RESIDENCE / HOME                31195
STREETS / HWY / ROAD / ALLEY    15698
PARKING LOTS / GARAGE            8533
COMMERCIAL / OFFICE BUILDING     6348
OTHER / UNKNOWN                  1211
CONVENIENCE STORE                1013
DEPARTMENT / DISCOUNT STORE       994
GOVERNMENT / PUBLIC BUILDING      961
RESTAURANTS                       937
HOTEL / MOTEL / ETC.              843
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2011:

RESIDENCE / HOME                24044
STREETS / HWY / ROAD / ALLEY    17430
PARKING LOTS / GARAGE            6842
COMMERCIAL / OFFICE BUILDING     5735
DEPARTMENT / DISCOUNT STORE      1370
GOVERNMENT / PUBLIC BUILDING     1276
BAR / NIGHT CLUB                 1192
OTHER / UNKNOWN                  1130
GROCERY / SUPERMARKET            1061
HOTEL / MOTEL / ETC.              958
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2012:

RESIDENCE / HOME                22698
STREETS / HWY / ROAD / ALLEY    17359
PARKING LOTS / GARAGE            6455
COMMERCIAL / OFFICE BUILDING     5981
DEPARTMENT / DISCOUNT STORE      1372
OTHER / UNKNOWN                  1302
GROCERY / SUPERMARKET            1274
BAR / NIGHT CLUB                 1187
GOVERNMENT / PUBLIC BUILDING     1071
RESTAURANTS                       900
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2013:

RESIDENCE / HOME                21758
STREETS / HWY / ROAD / ALLEY    16340
PARKING LOTS / GARAGE            6227
COMMERCIAL / OFFICE BUILDING     5617
OTHER / UNKNOWN                  1486
DEPARTMENT / DISCOUNT STORE      1368
GROCERY / SUPERMARKET            1327
BAR / NIGHT CLUB                 1152
HOTEL / MOTEL / ETC.             1041
GOVERNMENT / PUBLIC BUILDING     1025
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2014:

RESIDENCE / HOME                20423
STREETS / HWY / ROAD / ALLEY    14779
PARKING LOTS / GARAGE            5689
COMMERCIAL / OFFICE BUILDING     3543
OTHER / UNKNOWN                  2310
DEPARTMENT / DISCOUNT STORE      1614
GROCERY / SUPERMARKET            1348
HOTEL / MOTEL / ETC.             1101
BAR / NIGHT CLUB                  961
RESTAURANTS                       898
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2015:

RESIDENCE / HOME                19860
STREETS / HWY / ROAD / ALLEY    13782
PARKING LOTS / GARAGE            5688
OTHER / UNKNOWN                  2930
COMMERCIAL / OFFICE BUILDING     1893
DEPARTMENT / DISCOUNT STORE      1711
GROCERY / SUPERMARKET            1334
HOTEL / MOTEL / ETC.             1059
BAR / NIGHT CLUB                  906
RESTAURANTS                       876
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2016:

RESIDENCE / HOME                                  16165
STREETS / HWY / ROAD / ALLEY                      11461
PARKING LOTS / GARAGE                              4522
OTHER / UNKNOWN                                    2770
COMMERCIAL / OFFICE BUILDING                        971
HOTEL / MOTEL / ETC.                                921
DEPARTMENT / DISCOUNT STORE                         835
TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)      761
RESTAURANTS                                         744
BAR / NIGHT CLUB                                    693
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2017:

RESIDENCE / HOME                                  14931
STREETS / HWY / ROAD / ALLEY                      11033
PARKING LOTS / GARAGE                              4214
OTHER / UNKNOWN                                    2639
COMMERCIAL / OFFICE BUILDING                        856
RESTAURANTS                                         783
HOTEL / MOTEL / ETC.                                767
DEPARTMENT / DISCOUNT STORE                         716
TRANSPORTATION (AIR / BUS / TRAIN - TERMINALS)      705
PARK / PLAYGROUND                                   588
Name: Location Type, dtype: int64


Top ten location types with most crimes reported in 2018:

RESIDENCE / HOME                18233
STREETS / HWY / ROAD / ALLEY     9987
PARKING LOTS / GARAGE            5226
OTHER / UNKNOWN                  3175
DEPARTMENT / DISCOUNT STORE      1074
COMMERCIAL / OFFICE BUILDING     1041
RESTAURANTS                       990
HOTEL / MOTEL / ETC.              947
GROCERY / SUPERMARKET             830
BAR / NIGHT CLUB                  633
Name: Location Type, dtype: int64

In [18]:
for year in range(2009,2019):
    print(f'Top ten zip codes with most crimes reported in {year}: \n\n{df[df.index.year==year]["Zip Code"].value_counts().iloc[0:10]}\n\n')

Top ten zip codes with most crimes reported in 2009:

78741.0    7146
78745.0    5926
78753.0    5480
78744.0    5249
78758.0    5096
78723.0    4961
78704.0    3761
78702.0    3743
78752.0    3349
78751.0    2590
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2010:

78741.0    7180
78753.0    5789
78745.0    5559
78744.0    5214
78758.0    5161
78723.0    4355
78704.0    3732
78702.0    3433
78752.0    3113
78751.0    2685
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2011:

78701.0    9133
78741.0    5999
78704.0    5671
78753.0    5225
78702.0    4506
78758.0    4156
78745.0    3282
78748.0    2837
78744.0    2539
78723.0    2527
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2012:

78701.0    9151
78741.0    5839
78753.0    5585
78704.0    5513
78702.0    4490
78758.0    4048
78745.0    3207
78748.0    2901
78723.0    2376
78744.0    2344
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2013:

78701.0    8898
78741.0    5447
78753.0    5415
78704.0    5359
78702.0    4166
78758.0    4062
78745.0    3193
78748.0    2764
78723.0    2424
78744.0    2378
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2014:

78701.0    7999
78753.0    5194
78741.0    4944
78704.0    4640
78702.0    3970
78758.0    3831
78745.0    3035
78748.0    2897
78744.0    2261
78723.0    2172
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2015:

78701.0    7711
78704.0    4806
78753.0    4787
78741.0    4526
78758.0    3812
78702.0    3188
78745.0    2893
78748.0    2824
78744.0    2223
78723.0    2049
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2016:

78701.0    6151
78741.0    3633
78753.0    3244
78704.0    3228
78758.0    3022
78745.0    2540
78702.0    2366
78744.0    2149
78723.0    1988
78748.0    1796
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2017:

78701.0    5185
78741.0    3266
78753.0    3167
78704.0    2994
78758.0    2933
78745.0    2472
78702.0    2204
78744.0    1986
78723.0    1838
78748.0    1785
Name: Zip Code, dtype: int64


Top ten zip codes with most crimes reported in 2018:

78701.0    4321
78741.0    3714
78753.0    3600
78758.0    3551
78704.0    3336
78745.0    2911
78702.0    2433
78744.0    2343
78723.0    2321
78748.0    2042
Name: Zip Code, dtype: int64

In [19]:
dow = ["Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday","Sunday"]
print("Crimes reports by day of week")   
for day in range(0,7):
    print( f'Number of crime reports on {dow[day]}: {len(df[df.index.dayofweek==day])}')

Crimes reports by day of week
Number of crime reports on Monday: 85258
Number of crime reports on Tuesday: 84452
Number of crime reports on Wednesday: 84789
Number of crime reports on Thursday: 85995
Number of crime reports on Friday: 94754
Number of crime reports on Saturday: 92635
Number of crime reports on Sunday: 85553

In [20]:
for year in range(2009,2019):
    df_for_year = df[df.index.year == year ]
    print(f"\nFor {year}\n")
    for day in range(0,7):
        print( f'Number of crime reports on {dow[day]}: {len(df_for_year[df_for_year.index.dayofweek==day])}')

For 2009

Number of crime reports on Monday: 10452
Number of crime reports on Tuesday: 10214
Number of crime reports on Wednesday: 10461
Number of crime reports on Thursday: 10643
Number of crime reports on Friday: 11392
Number of crime reports on Saturday: 11068
Number of crime reports on Sunday: 10188

For 2010

Number of crime reports on Monday: 10140
Number of crime reports on Tuesday: 10064
Number of crime reports on Wednesday: 9954
Number of crime reports on Thursday: 10238
Number of crime reports on Friday: 11285
Number of crime reports on Saturday: 10870
Number of crime reports on Sunday: 9753

For 2011

Number of crime reports on Monday: 8664
Number of crime reports on Tuesday: 8845
Number of crime reports on Wednesday: 8915
Number of crime reports on Thursday: 9138
Number of crime reports on Friday: 10430
Number of crime reports on Saturday: 10658
Number of crime reports on Sunday: 9203

For 2012

Number of crime reports on Monday: 8894
Number of crime reports on Tuesday: 8583
Number of crime reports on Wednesday: 8845
Number of crime reports on Thursday: 8994
Number of crime reports on Friday: 9833
Number of crime reports on Saturday: 10033
Number of crime reports on Sunday: 9360

For 2013

Number of crime reports on Monday: 8624
Number of crime reports on Tuesday: 8741
Number of crime reports on Wednesday: 8433
Number of crime reports on Thursday: 8592
Number of crime reports on Friday: 9835
Number of crime reports on Saturday: 9377
Number of crime reports on Sunday: 8793

For 2014

Number of crime reports on Monday: 7899
Number of crime reports on Tuesday: 8220
Number of crime reports on Wednesday: 8125
Number of crime reports on Thursday: 8052
Number of crime reports on Friday: 9009
Number of crime reports on Saturday: 8857
Number of crime reports on Sunday: 7963

For 2015

Number of crime reports on Monday: 7955
Number of crime reports on Tuesday: 7781
Number of crime reports on Wednesday: 7914
Number of crime reports on Thursday: 8035
Number of crime reports on Friday: 8317
Number of crime reports on Saturday: 8146
Number of crime reports on Sunday: 7922

For 2016

Number of crime reports on Monday: 6375
Number of crime reports on Tuesday: 6159
Number of crime reports on Wednesday: 6140
Number of crime reports on Thursday: 6225
Number of crime reports on Friday: 6989
Number of crime reports on Saturday: 6759
Number of crime reports on Sunday: 6349

For 2017

Number of crime reports on Monday: 5939
Number of crime reports on Tuesday: 5760
Number of crime reports on Wednesday: 5851
Number of crime reports on Thursday: 5897
Number of crime reports on Friday: 6453
Number of crime reports on Saturday: 6084
Number of crime reports on Sunday: 5997

For 2018

Number of crime reports on Monday: 6839
Number of crime reports on Tuesday: 6408
Number of crime reports on Wednesday: 6578
Number of crime reports on Thursday: 6674
Number of crime reports on Friday: 7172
Number of crime reports on Saturday: 7127
Number of crime reports on Sunday: 6528

In [21]:
months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
print("Crimes reports by month of year")   
for month in range(1,13):
    print( f'Number of crime reports on {months[month-1]}: {len(df[df.index.month==month])}')

Crimes reports by month of year
Number of crime reports on Jan: 56179
Number of crime reports on Feb: 49002
Number of crime reports on Mar: 59570
Number of crime reports on Apr: 51936
Number of crime reports on May: 51304
Number of crime reports on Jun: 49151
Number of crime reports on Jul: 51007
Number of crime reports on Aug: 50021
Number of crime reports on Sep: 47017
Number of crime reports on Oct: 50093
Number of crime reports on Nov: 48235
Number of crime reports on Dec: 49921

In [23]:
year_group_by = df.groupby("Datetime")

In [25]:
year_group_by["Highest Offense Description"].value_counts()

Datetime    Highest Offense Description
2009-01-01  IDENTITY THEFT                 58
            THEFT                          32
            HARASSMENT                     28
            FAMILY DISTURBANCE             23
            CRIMINAL MISCHIEF              21
                                           ..
2019-04-13  POSS OF DRUG PARAPHERNALIA      1
            RUNAWAY CHILD                   1
            SUSPICIOUS PERSON               1
            THEFT FROM PERSON               1
            THEFT OF LICENSE PLATE          1
Name: Highest Offense Description, Length: 195336, dtype: int64